### ISSUE TITLE
Any interest in adding to krew?

### ISSUE THREAD

**Issue by jmreicha** [sysdiglabs/kubectl-capture#1]
Looks like this plugin would be a great fit for adding to the [`krew`](https://github.com/GoogleContainerTools/krew-index) package manager.

**Comment by nestorsalceda** [comment]
Yes, It would be great.

I start to work on that in a few days. I will update here when finished.

Thanks!

**Comment by corneliusweig** [comment]
@nestorsalceda just a polite reminder that it would be great to have this in `krew`.

**Comment by nestorsalceda** [comment]
Yeah! I love it, let me to find some time to schedule it for Q4

Thanks for the reminder @corneliusweig :)

**Comment by corneliusweig** [comment]
@nestorsalceda Since this is a bash script, the main this you have to do is to create a github release, so that there's a tarball to archive.

**Comment by nestorsalceda** [comment]
The kubectl-capture plugin was added to krew-index, so I think we can close this issue :)

Thanks agains for your support @corneliusweig !

**Comment by glensc** [comment]
@nestorsalceda please update project readme as well, how to install it? what is the name you added to index? link to PR that added it?
